from __future__ import print_function
import GPinv
import numpy as np
import unittest
import tensorflow as tf
from make_LosMatrix import make_LosMatrix, AbelLikelihood

class Test_gpmc(unittest.TestCase):
    def test(self):
        """
        Abel inversion for the synthetic data.
        The observation y is generated by the latent function f
        y = A f + e
        with
        A = los-length-matrix
        """
        rng = np.random.RandomState(0)
        n = 30
        N = 40
        # radial position. 0~1
        r = np.linspace(0, 1., n)
        # height of LOS. -0.9~1
        z = np.linspace(-0.9, 0.9, N)
        # observation results at each Z
        y = np.zeros((N, 1))
        # noise amplitude on the observation
        e = 0.1
        # synthetic latent function
        f = np.exp(-(r-0.5)*(r-0.5)/0.1) + np.exp(-(r+0.5)*(r+0.5)/0.1)
        # constructing LOS-matrix
        A = make_LosMatrix(r,z)
        # synthetic signals
        y = np.dot(A, f) + e*rng.randn(N)
        # likelihood
        likelihood = AbelLikelihood(A)
        kern=GPinv.kernels.RBF(1) + GPinv.kernels.White(1) # the additional jitter is necessary.
        kern.white.variance = 1.0e-5

        model = GPinv.nonlinear_model.GPMC(
            X=r.reshape(-1,1), Y=y.reshape(-1,1),
            kern=kern,
            mean_function=GPinv.mean_functions.Constant(np.ones(1)),
            likelihood=likelihood)

        samples = model.sample(num_samples=500, Lmax=20, epsilon=0.01, verbose=False)
        # check the noise value
        noise = []
        for s in samples[200:]:
            model.set_state(s)
            noise.append(model.likelihood.variance.value)
        noise_avg = np.mean(noise)
        print(noise_avg)
        self.assertTrue(np.allclose(noise_avg, e*e, rtol=0.2))

if __name__ == '__main__':
    unittest.main()
